### ISSUE TITLE
Theme footer

### ISSUE THREAD

**Issue by soniCaH** [soniCaH/drupalcamp-2015#11]
Theme the footer

**Comment by soniCaH** [comment]
Done

**Comment by soniCaH** [comment]
![screen shot 2015-10-05 at 11 15 31](https://cloud.githubusercontent.com/assets/789034/10276831/66c63b2a-6b52-11e5-81bf-5ad2d364df30.png)

**Comment by bramvandenbulcke** [comment]
The png background is too large (+/- 2MB for the largest ones). Attached some smaller jpg's (ten times smaller). 

![paper-old-bg_xl](https://cloud.githubusercontent.com/assets/8631196/10366149/b55719d0-6dc8-11e5-932e-d0f1a879c0db.jpg)
![paper-old-bg_l](https://cloud.githubusercontent.com/assets/8631196/10366152/bc077b3a-6dc8-11e5-8ab1-4d36de89e99f.jpg)
![paper-old-bg_m](https://cloud.githubusercontent.com/assets/8631196/10366155/c180d52a-6dc8-11e5-9c0d-bc262132f2d2.jpg)
![paper-old-bg_s](https://cloud.githubusercontent.com/assets/8631196/10366157/c53444ea-6dc8-11e5-86d6-61d8b371f365.jpg)

**Comment by soniCaH** [comment]
Replaced files.
Please re-open ticket and assign next time (normally I delete all github mails directly ;-))
