### ISSUE TITLE
Create a page with own unprocessed sessions

### ISSUE THREAD

**Issue by soniCaH** [soniCaH/drupalcamp-2015#32]
On "my account" there's a link to My Sessions, but for regular users nothing shows.

View is set to display all sessions with conditional filter on the user and has a global permission of "view own unpublished content", which seems fine, but does not work.

**Comment by bramvandenbulcke** [comment]
Is this fixed by changing the Filter to Content: Status (= Accepted or Unprocessed)?

**Comment by soniCaH** [comment]
Had to recreate the view for some weird reason
