### ISSUE TITLE
PAGE: Create sponsors page

### ISSUE THREAD

**Issue by soniCaH** [soniCaH/drupalcamp-2015#9]
Create a sponsor page with different blocks for each level of sponsoring.
Follow-up by #10

**Comment by bramvandenbulcke** [comment]
In de issue queue van vorig jaar zag ik ook de organizing partners / support (m.n. KHLeuven) opgelijst staan. 

Is daar plaats voor?

**Comment by soniCaH** [comment]
Die wordt opgenomen zodra toegevoegd (is een sponsor level ‘partner’ voorzien)
Komt in de footer en op de sponsor pagina tussen de silver sponsors.
